name: Documentation

on: 
  push:
    branches: [ main]
    paths: 
      - "tidepredictor/**"
      - ".github/workflows/docs.yml"
      - "docs/**"
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.5.15"
        
    - name: Install library
      run: |
        uv sync --group docs
    
    - name: Copy constituents to standard data dir
      run: |
          mkdir -p ~/.local/share/tidepredictor
          cp tests/data/*.nc ~/.local/share/tidepredictor/
    
    - name: Build documentation
      run: |
        make docs

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_site/

    - name: Publish to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site/
      
