# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Full test

on:
  push:
    branches: [main]
    paths: 
      - "tidepredictor/**"
      - ".github/workflows/full_test.yml"
      - "tests/**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1 # Fail fast if there are any linting errors
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.15"
        
      - name: Install library
        run: |
          uv sync --group test

      - name: Copy constituents to standard data dir
        run: |
          mkdir -p ~/.local/share/tidepredictor
          cp tests/data/elevation ~/.local/share/tidepredictor/
      - name: Static type check
        run: make typecheck
      - name: Test with pytest
        run: make test
